### ISSUE TITLE
Do not edit providers.tf

### ISSUE THREAD

**Issue by s-irvine** [kubernetes-simulator/simulator#102]
**Describe the bug**
Editing `providers.tf`  prevents using a read only mount in the container. This prevents the  ` simulator infra create` command from working as it edits a file on a read-only filesystem. Issue found when working #100 

**To Reproduce**
1. Mount a local terraform dir into the container using `-v $(shell pwd)/terraform:/app/terraform`
2. Run `simulator infra create`

**Expected behavior**
We should be able to mount this directory into the container as read-only to facilitate local workflow and prevent accidental edits going back to the host fs.

These links may help: 
[tf docs](https://www.terraform.io/docs/backends/types/s3.html#using-the-s3-remote-state)
[Github issue](https://github.com/hashicorp/terraform/issues/13022#issuecomment-294262392)

**Comment by jondkent** [comment]
Has this been address by issue #100 ?

**Comment by s-irvine** [comment]
Nope, before #100 this wasn't a problem as the edited files stayed in the container so edits to `terraform/deployments/AWS/providers.tf` could find their way back to the host. Since #100 there is the possibility of someone committing their bucket name back to the repo. This won't impact the functionality of simulator it's just annoying and embarrassing.

**Comment by jondkent** [comment]
Unfortunately this file need to be written to configure the S3 bucket to use in terraform. 

Potentially this could be reverted as part of the exit clean up, but there could be an issue with that, so would be need testing obviously

**Comment by jondkent** [comment]
Main issue here is that we need to have the ability to re-run `make run` and still have access to the S3 bucket.  This is to cover the event that someone exits out of the simulator too early and wants to be able to run simulator again to destroy the hanging infrastructure

**Comment by raoulmillais** [comment]
As discussed with @pi-unnerup on a call - In order to mount the terraform directory as readonly we need to write the settings/bastion.tfvars file to a different location inside the container.  I think that we need a separate ticket for that work and keep the scope of this ticket to stopping writing the providers.tf file.
