### ISSUE TITLE
Infra doesn't build from new init.

### ISSUE THREAD

**Issue by pi-unnerup** [kubernetes-simulator/simulator#117]
**Describe the bug**
When starting a run from no bucket and creating a bucket with a new name, you can not create infra.

Error message: 
Error: Failed to get existing workspaces: S3 bucket does not exist.

**To Reproduce**
from host, delete simulator yaml. 

$simulator init
$simulator infra create

**Comment by jondkent** [comment]
related to pull request #96

**Comment by pi-unnerup** [comment]
rm -R terraform/deployments/AWS/.terraform

fixes short term

**Comment by jondkent** [comment]
When I following your instruction above I get the following

<pre>
launch@launch:/app$ simulator init
panic: Error reading config file: Config File "simulator" Not Found in "[/home/launch/.kubesim]"

goroutine 1 [running]:
github.com/controlplaneio/simulator-standalone/cmd.initConfig()
	/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:75 +0x24d
github.com/spf13/cobra.(*Command).preRun(0xc0002e6280)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x49
github.com/spf13/cobra.(*Command).execute(0xc0002e6280, 0x11a7ce8, 0x0, 0x0, 0xc0002e6280, 0x11a7ce8)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x148
github.com/spf13/cobra.(*Command).ExecuteC(0x11819a0, 0xc0002e7400, 0xc0002e6c80, 0xc0002e6500)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2f8
github.com/spf13/cobra.(*Command).Execute(0x11819a0, 0x0, 0xc000205f58)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864 +0x2b
github.com/controlplaneio/simulator-standalone/cmd.Execute(0xb, 0xbab7df)
	/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:109 +0x27
main.main()
	/go/src/github.com/controlplaneio/simulator-standalone/main.go:13 +0x26
launch@launch:/app$
</pre>

Which I would expect as the `simulator.yaml` no longer exists.

I think you reproduction instructions are not correct.

**Comment by jondkent** [comment]
If I run the following I can't reproduce the error:

In terminal 1
<pre>
cat /dev/null > ~/.kubesim/simulator.yaml
</pre>

In terminal 2
<pre>
simulator init
[enter unique bucket to create]
simulator infra create
</pre>

All works as expected

**Comment by jondkent** [comment]
Got this error now when deleting the simulator.yaml file before running `make run`
