### ISSUE TITLE
etcd open access

### ISSUE THREAD

**Issue by jondkent** [kubernetes-simulator/simulator#124]
**Describe the bug**
etcd is currently accessible by all nodes with the default kubeadm installation.

**Expected behavior**
Access to etcd should be restricted to the api server

**Comment by s-irvine** [comment]
This will break several of our scenarios. While it is best practice, we are deliberately showing poor practice as a teaching mechanism so I feel this is unnecessary.

**Comment by jondkent** [comment]
don't disagree, put here largely the ensure this was known
