### ISSUE TITLE
CAP_NET_RAW Enabled

### ISSUE THREAD

**Issue by jondkent** [kubernetes-simulator/simulator#125]
**Describe the bug**
CAP_NET_RAW is enabled by default for pods.  If an attacker manages to compromise a pod, they could potentially take advantage of this capability to perform network attacks on other pods running on the same node

**Expected behavior**
Should this be enabled by default?

**Comment by s-irvine** [comment]
I feel overly hardening these nodes will give a false sense of security to those using our clusters if they try something and it doesn't work. CAP_NET_RAW is a good idea for a complex scenario so I'd prefer to highlight it that way rather than fix it in the background without a user seeing.

**Comment by jondkent** [comment]
don't disagree, put here largely the ensure this was known
