### ISSUE TITLE
Require Signed Commits in PRs

### ISSUE THREAD

**Issue by s-irvine** [kubernetes-simulator/simulator#136]
We should require all commits to PRs that will be merged into master should be signed. This will give us assurance commits are made by the account that is claiming to make them. 

We can enable this option in the branch protection settings for master and we should do this as a matter of best practice.

**Comment by jondkent** [comment]
Agree this would be a good approach

**Comment by s-irvine** [comment]
We may as well enable this when #88 becomes enforced.
