### ISSUE TITLE
Some scenarios time out waiting for pods to be initialised

### ISSUE THREAD

**Issue by pi-unnerup** [kubernetes-simulator/simulator#148]
**Describe the bug**
When running some scenarios (secret-high-ground, possibly others) they hang and timeout on waiting for pods to be initialised. 

**Additional context (optional)**
Was replicated by myself and Jon Knox on the same network. Might be worth testing on different network.

**Comment by pi-unnerup** [comment]
note: found to be an issue in alpine.

**Comment by jondkent** [comment]
Added dying label as this appears to be not related to simulator code

**Comment by s-irvine** [comment]
@pi-unnerup Was this fixed by #153?
