### ISSUE TITLE
Standardise bash configiurations

### ISSUE THREAD

**Issue by raoulmillais** [kubernetes-simulator/simulator#159]
Use the same bash configurations for all instances and containers:

* [x] Prompt command / PS1
* [x] inputrc
* [x] aliases
* [x] bash_completion

Take from the attack/launch containers which @sublimino modified already to make more friendly

**Comment by s-irvine** [comment]
We don't use a bash_completion anywhere so that's been standardised by not having one.

**Comment by sublimino** [comment]
This is where we [source bash completion](https://github.com/kubernetes-simulator/simulator/blob/cd38112b347a03d082f34afcc24ad115bf7ddf44/attack/scripts/bashrc#L22), please ensure it's installed everywhere : ]
