### ISSUE TITLE
Setup jenkins/github to allow testing PRs from contributors

### ISSUE THREAD

**Issue by raoulmillais** [kubernetes-simulator/simulator#186]
Goals:

1. Fast feedback for contributions - run as much as possible that does not have potential to do malicious things automatically using github actions
2. Provide a gated means to run the full acceptance test suite on a PR that has been visually verified by a maintainer on internal CI infrastructure e.g. by issuing a comment on the PR

Nice to have:

1. Reduce duplication of CI / build logic - try to avoid specifying pipeline twice (once for GH actions, once for jenkins)

Possible approaches:

1. Update github actions to run golang lint and unit tests

**Comment by alpe** [comment]
This can be a 2 step process. IMHO quick feedback from the github worklfow would help any contributor to be on track. Unit tests and compilation steps are usually fast enough and free of charge on build infrastructure like github workflow.
Full acceptance tests are very nice though but with a manual gate this can become a slow process when unit tests would fail already.

**Comment by raoulmillais** [comment]
> This can be a 2 step process. IMHO quick feedback from the github worklfow would help any contributor to be on track. Unit tests and compilation steps are usually fast enough and free of charge on build infrastructure like github workflow.
> Full acceptance tests are very nice though but with a manual gate this can become a slow process when unit tests would fail already.

thanks I updated the issue
