### ISSUE TITLE
Issue clearer error messages if no scenario

### ISSUE THREAD

**Issue by pi-unnerup** [kubernetes-simulator/simulator#230]
For task and hint related helpers, issue an error message like "you have not started a scenario" if there is no scenario. Currently the error message is just "error:	Cannot read property '1' of undefined"

**Comment by s-irvine** [comment]
Having investigated this a bit it looks like the BASH helpers in the `.bashrc` all handle an undefined scenario in some form or another. It's the node.js helpers which need updating.
