### ISSUE TITLE
Simulator crashes with  "make: *** [run] Error 15"  when start to use.

### ISSUE THREAD

**Issue by cc83851** [kubernetes-simulator/simulator#237]
The simulator container dies as soon as one starts to interact with it via a shell in a launch container with the error:

make: *** [run] Error 157

I have built and spun up the simulator container as per the README.md file (i.e. cloned repository and run "make run". The simulator image builds fine, the container spins up and I am dropped you into a shell in the launch container, as expected. However, as soon as I interact with that shell (type a space, hit return, anything) the container dies and the above error appears on the command line.

The problem is occurring on:
macOS Catalina (10.15.3)
Docker Desktop for Mac (Docker version 19.03.5, build 633a0ea)
Simulator version: current "dev" version

To reproduce 
1) Clone simulator repository
2) Set AWS environment variables for my account (e.g. region)
3) Run "run make" (this successfully builds the image, spins up the container and drop me into a shell on it)
4) Interact with the shell in any way, and the container will crash, with the error
make: *** [run] Error 157

I cannot get as far as running any of the simulator commands.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/61393208/75140915-c0c82e00-56e7-11ea-9c71-052e6651319d.png">

**Comment by jondkent** [comment]
Hi,

Thanks for the issue.  I've tried to reproduce and `simulator` is working fine for me.

I'm using the current master branch (638897a2cad68363f4123e7e251e727a03434145).  This big difference between you setup and mine is the docker version.

Docker : 2.2.0.3
MacOS: 10.15.1

Minor difference in MacOs verison, wouldn't expect that to be an issue.

Can you upgrade your Docker?

Thanks,

Jon

**Comment by cc83851** [comment]
Thank you for your quick response. My colleague was also unable to re-produce on his Mac also running same version of macOS as I am. I just rebooted my laptop and the problem has now gone away. Not helpful in terms of tracking it down, but at least I have a workaround in case it re-occurs.
