### ISSUE TITLE
Break up attack welcome message

### ISSUE THREAD

**Issue by raoulmillais** [kubernetes-simulator/simulator#253]
The welcome message is a wall of text currently and we don't enforce using the helpers.  We should:
* Prevent using hints / sshing before a task has been started
* Show hint usage and scoring info only after first task is started

**Comment by jondkent** [comment]
I suggest splitting this out somewhat

- Welcome
- Challenge
- Commands

Then rather than getting eveything when you type `welcome` you can request the specific section.

Current lines 245-254 can be tightened up by removing the wordage  (too much infomation)
