### ISSUE TITLE
Etcd-inverted-edge reports an error when perturbing

### ISSUE THREAD

**Issue by raoulmillais** [kubernetes-simulator/simulator#271]
```
ERRO[2020-03-25T11:34:36Z] jq: error (at <stdin>:3976): Cannot iterate over null (null)  Args="[--master 172.31.2.103 --bastion 3.8.8.200 --nodes 172.31.2.23,172.31.2.70 etcd-inverted-wedge]" Command=./perturb.sh
```

It perturbs fine though.  We should diagnose the error and either fix or remove it.

**Comment by s-irvine** [comment]
This is extremely intermittent and very hard to reproduce. I have not yet managed to to reliably cause it so more information is probably needed.
