### ISSUE TITLE
Cloud agnostic scenarios ?!

### ISSUE THREAD

**Issue by ayoubeddafali** [kubernetes-simulator/simulator#297]
Are the provided scenarios cloud agnostic, meaning if I have my cluster setup in Digital Ocean for example, can I run those scenarios there or not ? 

Thanks

**Comment by s-irvine** [comment]
Hi @ayoubeddafali thanks for your issue but none of the scenarios are cloud agnostic at the moment. Since all of the scenarios create some deliberately vulnerable infrastructure they aren't something I'd recommend running on your own cluster.

**Comment by jondkent** [comment]
Closing
