### ISSUE TITLE
Apparent Logging Issue

### ISSUE THREAD

**Issue by abdullahgarcia** [kubernetes-simulator/simulator#31]
When executing:

**simulator infra destroy**

Output:

`launch@launch:/app$ simulator infra destroy
1.572539731390471e+09	INFO	simulator/terraform.go:50	Running terraform init
Initializing modules...
- Ami in ../../modules/AWS/Ami
- Bastion in ../../modules/AWS/Bastion
- InternalNode in ../../modules/AWS/InternalNode
- Kubernetes in ../../modules/AWS/Kubernetes
- Networking in ../../modules/AWS/Networking
- S3Storage in ../../modules/AWS/S3Storage
- SecurityGroups in ../../modules/AWS/SecurityGroups
- SshKey in ../../modules/AWS/SshKey

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to get existing workspaces: InvalidBucketName: The specified bucket is not valid.
	status code: 400, request id: 820FC0434E1F175B, host id: TA2hUu6hFa9Vt0ZZi3nLnHMz6mfaHpL0z/nNs/qIQLWfox08SqYmOFtwnkAkTO0lZQOLj8bamfI=

1.57253973303412e+09	ERROR	cmd/infra.go:96	Error destroying infrastructure{"error": "Error initialising: Error initialising terraform: Error waiting for child process terraform: exit status 1", "errorVerbose": "exit status 1\nError waiting for child process terraform\ngithub.com/controlplaneio/simulator-standalone/pkg/util.Run\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/util/run.go:58\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Terraform\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:42\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.InitIfNeeded\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:51\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Destroy\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:137\ngithub.com/controlplaneio/simulator-standalone/cmd.newDestroyCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/infra.go:94\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:105\nmain.main\n\t/go/src/github.com/controlplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333\nError initialising terraform\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.InitIfNeeded\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:53\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Destroy\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:137\ngithub.com/controlplaneio/simulator-standalone/cmd.newDestroyCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/infra.go:94\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:105\nmain.main\n\t/go/src/github.com/controlplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333\nError initialising\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Destroy\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:139\ngithub.com/controlplaneio/simulator-standalone/cmd.newDestroyCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/infra.go:94\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:105\nmain.main\n\t/go/src/github.com/controlplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333"}
github.com/controlplaneio/simulator-standalone/cmd.newDestroyCommand.func1
	/go/src/github.com/controlplaneio/simulator-standalone/cmd/infra.go:96
github.com/spf13/cobra.(*Command).execute
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/controlplaneio/simulator-standalone/cmd.Execute
	/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:105
main.main
	/go/src/github.com/controlplaneio/simulator-standalone/main.go:13
runtime.main
	/usr/lib/go-1.11/src/runtime/proc.go:201
Error: Error initialising: Error initialising terraform: Error waiting for child process terraform: exit status 1
Usage:
  simulator infra destroy [flags]

Flags:
  -h, --help   help for destroy

Global Flags:
  -c, --config-file string     Path to the simulator config file
  -l, --loglevel string        Level of detail in output logging (default "info")
  -s, --scenarios-dir string   Path to a directory containing a scenario manifest (default "./simulation-scripts")
  -b, --state-bucket string    The name of the s3 bucket to use for remote-state.  Must be globally unique
  -t, --tf-dir string          Path to a directory containing the infrastructure scripts (default "./terraform/deployments/AWS")

Error initialising: Error initialising terraform: Error waiting for child process terraform: exit status 1`

Verification:

**simulator config get state-bucket**

`launch@launch:/app$ simulator config get state-bucket
1.5725399745775201e+09	INFO	cmd/config.go:20	state-bucket = agarcia-scenarios-testing\n`

Verification:

**simulator infra status**

`launch@launch:/app$ simulator infra status
1.5725400588509696e+09	INFO	simulator/terraform.go:50	Running terraform init
Initializing modules...

Initializing the backend...

Error: Failed to get existing workspaces: InvalidBucketName: The specified bucket is not valid.
	status code: 400, request id: F4A02C55E37B353F, host id: NWtdZPxehMsDzcauFJ7MmBUkHZZGNKFOtebH9Ipjj1qNdCiIWqkwN4/hso0PtNbcdwKTqrdPZnU=

1.5725400604029083e+09	ERROR	cmd/infra.go:62	Error getting status of infrastructure	{"error": "Error initialising: Error initialising terraform: Error waiting for child process terraform: exit status 1", "errorVerbose": "exit status 1\nError waiting for child process terraform\ngithub.com/controlplaneio/simulator-standalone/pkg/util.Run\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/util/run.go:58\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Terraform\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:42\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.InitIfNeeded\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:51\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Status\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:113\ngithub.com/controlplaneio/simulator-standalone/cmd.newStatusCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/infra.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:105\nmain.main\n\t/go/src/github.com/controlplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333\nError initialising terraform\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.InitIfNeeded\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:53\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Status\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:113\ngithub.com/controlplaneio/simulator-standalone/cmd.newStatusCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/infra.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:105\nmain.main\n\t/go/src/github.com/controlplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333\nError initialising\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Status\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/terraform.go:115\ngithub.com/controlplaneio/simulator-standalone/cmd.newStatusCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/infra.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:105\nmain.main\n\t/go/src/github.com/controlplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333"}
github.com/controlplaneio/simulator-standalone/cmd.newStatusCommand.func1
	/go/src/github.com/controlplaneio/simulator-standalone/cmd/infra.go:62
github.com/spf13/cobra.(*Command).execute
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/controlplaneio/simulator-standalone/cmd.Execute
	/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:105
main.main
	/go/src/github.com/controlplaneio/simulator-standalone/main.go:13
runtime.main
	/usr/lib/go-1.11/src/runtime/proc.go:201
Error: Error initialising: Error initialising terraform: Error waiting for child process terraform: exit status 1
Usage:
  simulator infra status [flags]

Flags:
  -h, --help   help for status

Global Flags:
  -c, --config-file string     Path to the simulator config file
  -l, --loglevel string        Level of detail in output logging (default "info")
  -s, --scenarios-dir string   Path to a directory containing a scenario manifest (default "./simulation-scripts")
  -b, --state-bucket string    The name of the s3 bucket to use for remote-state.  Must be globally unique
  -t, --tf-dir string          Path to a directory containing the infrastructure scripts (default "./terraform/deployments/AWS")

Error initialising: Error initialising terraform: Error waiting for child process terraform: exit status 1`

**Comment by raoulmillais** [comment]
Fixed by reverting the IP detection change
