### ISSUE TITLE
Docs: Improve how documentation is generated

### ISSUE THREAD

**Issue by raoulmillais** [kubernetes-simulator/simulator#51]
We should think about solving these problems:

* Why isn't this automatic?
* How to improve the templating so that bash can be included inline without throwing the templating system - it uses bash var substitution which is limiting
* How to reduce commit noise with doc generation
* ~~`godocdown` is now broken .. it is unmaintained and doesn't use gomodules and a downstream dependency has disappeared causing `make dep` to fail.  As much as I dislike godoc, I think we should remove the API docs from the repo and lean on using godoc.org for the golang docs~~

**Comment by jondkent** [comment]
I'd suggest going to a plain old README.md file, rather than trying to make it dynamic, as I'm not convinced the overhead at the moment is worth it

**Comment by jondkent** [comment]
moved documentation to static file from templates, resolved in PR #58
