### ISSUE TITLE
Getting `simulator scenario launch` errors when current user IP doesn't match security group rule.

### ISSUE THREAD

**Issue by sublimino** [kubernetes-simulator/simulator#56]
1. Create infrastructure from IP 1
1. Connect from IP 2
1. Run `simulator scenario launch node-shock-tactics`
1. SSH timeout is long, then errors as the TCP connection times out at the security group

Fix:

1. Run `simulator infra create` a second time when connected to IP 2 -- this creates the appropriate security group rules and then scenario deployment works

<details>
  <summary>Debug output:</summary>

	
	1.5733158573249292e+09  INFO    simulator/launch.go:61  Setting up the "Node Shock Tactics" scenario on the cluster
	ssh: connect to host 3.9.118.211 port 22: Connection timed out
	[2019-11-09T16:13:08+0000] ./perturb.sh: No hash found
	[2019-11-09T16:13:08+0000] ./perturb.sh: Found scenario 
	[2019-11-09T16:13:08+0000] ./perturb.sh: Running scenario/node-shock-tactics/ against 172.31.2.37
	Connection timed out during banner exchange
	[2019-11-09T16:13:11+0000] ./perturb.sh: Cannot connect to 172.31.2.37
	1.5733159911121545e+09  ERROR   cmd/scenario.go:54      Error launching scenario        {"error": "Error running perturb with simulator.PerturbOptions{Bastion:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
	0x0, 0x0, 0xff, 0xff, 0x3, 0x9, 0x76, 0xd3}, Master:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x25}, Slaves:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
	, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x33}, net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x2b}}, ScenarioName:\"node-shock-tactics\"}: Error waiting for child pr
	ocess ./perturb.sh: exit status 3", "errorVerbose": "exit status 3\nError waiting for child process ./perturb.sh\ngithub.com/controlplaneio/simulator-standalone/pkg/util.Run\n\t/go/src/github.com/controlpla
	neio/simulator-standalone/pkg/util/run.go:58\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Perturb\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/perturb.go:76\ngith
	ub.com/controlplaneio/simulator-standalone/pkg/simulator.Launch\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/launch.go:62\ngithub.com/controlplaneio/simulator-standalone/cmd.newSc
	enarioLaunchCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/scenario.go:49\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/comm
	and.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/build/go/pkg/mod/github.com/
	spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:109\nmain.main\n\t/go/src/github.com/contr
	olplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333\nError running perturb with simulator.Per
	turbOptions{Bastion:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0x3, 0x9, 0x76, 0xd3}, Master:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0
	x25}, Slaves:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x33}, net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x2b}
	}, ScenarioName:\"node-shock-tactics\"}\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Launch\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/launch.go:64\ngithub.com/
	controlplaneio/simulator-standalone/cmd.newScenarioLaunchCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/scenario.go:49\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/
	go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).
	Execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.
	
	go:109\nmain.main\n\t/go/src/github.com/controlplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1
	333"}```
	1.5733158573249292e+09  INFO    simulator/launch.go:61  Setting up the "Node Shock Tactics" scenario on the cluster
	ssh: connect to host 3.9.118.211 port 22: Connection timed out
	[2019-11-09T16:13:08+0000] ./perturb.sh: No hash found
	[2019-11-09T16:13:08+0000] ./perturb.sh: Found scenario 
	[2019-11-09T16:13:08+0000] ./perturb.sh: Running scenario/node-shock-tactics/ against 172.31.2.37
	Connection timed out during banner exchange
	[2019-11-09T16:13:11+0000] ./perturb.sh: Cannot connect to 172.31.2.37
	1.5733159911121545e+09  ERROR   cmd/scenario.go:54      Error launching scenario        {"error": "Error running perturb with simulator.PerturbOptions{Bastion:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
	0x0, 0x0, 0xff, 0xff, 0x3, 0x9, 0x76, 0xd3}, Master:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x25}, Slaves:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
	, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x33}, net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x2b}}, ScenarioName:\"node-shock-tactics\"}: Error waiting for child pr
	ocess ./perturb.sh: exit status 3", "errorVerbose": "exit status 3\nError waiting for child process ./perturb.sh\ngithub.com/controlplaneio/simulator-standalone/pkg/util.Run\n\t/go/src/github.com/controlpla
	neio/simulator-standalone/pkg/util/run.go:58\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Perturb\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/perturb.go:76\ngith
	ub.com/controlplaneio/simulator-standalone/pkg/simulator.Launch\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/launch.go:62\ngithub.com/controlplaneio/simulator-standalone/cmd.newSc
	enarioLaunchCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/scenario.go:49\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/comm
	and.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/build/go/pkg/mod/github.com/
	spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:109\nmain.main\n\t/go/src/github.com/contr
	olplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333\nError running perturb with simulator.Per
	turbOptions{Bastion:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0x3, 0x9, 0x76, 0xd3}, Master:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0
	x25}, Slaves:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x33}, net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x2b}
	}, ScenarioName:\"node-shock-tactics\"}\ngithub.com/controlplaneio/simulator-standalone/pkg/simulator.Launch\n\t/go/src/github.com/controlplaneio/simulator-standalone/pkg/simulator/launch.go:64\ngithub.com/
	controlplaneio/simulator-standalone/cmd.newScenarioLaunchCommand.func1\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/scenario.go:49\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/build/
	go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).
	Execute\n\t/home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/controlplaneio/simulator-standalone/cmd.Execute\n\t/go/src/github.com/controlplaneio/simulator-standalone/cmd/root.
	
	go:109\nmain.main\n\t/go/src/github.com/controlplaneio/simulator-standalone/main.go:13\nruntime.main\n\t/usr/lib/go-1.11/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/lib/go-1.11/src/runtime/asm_amd64.s:1
	333"}
	github.com/controlplaneio/simulator-standalone/cmd.newScenarioLaunchCommand.func1
	        /go/src/github.com/controlplaneio/simulator-standalone/cmd/scenario.go:54
	github.com/spf13/cobra.(*Command).execute
	        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
	github.com/spf13/cobra.(*Command).ExecuteC
	        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
	github.com/spf13/cobra.(*Command).Execute
	        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
	github.com/controlplaneio/simulator-standalone/cmd.Execute
	        /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:109
	main.main
	        /go/src/github.com/controlplaneio/simulator-standalone/main.go:13
	runtime.main
	        /usr/lib/go-1.11/src/runtime/proc.go:201
	```
	
	
	github.com/controlplaneio/simulator-standalone/cmd.newScenarioLaunchCommand.func1
	        /go/src/github.com/controlplaneio/simulator-standalone/cmd/scenario.go:54
	github.com/spf13/cobra.(*Command).execute
	        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
	github.com/spf13/cobra.(*Command).ExecuteC
	        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
	github.com/spf13/cobra.(*Command).Execute
	        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
	github.com/controlplaneio/simulator-standalone/cmd.Execute
	        /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:109
	main.main
	        /go/src/github.com/controlplaneio/simulator-standalone/main.go:13
	runtime.main
	        /usr/lib/go-1.11/src/runtime/proc.go:201

	
	</details>

**Comment by raoulmillais** [comment]
We should exit perturb early with a well-known status code so we can advise the user in a more friendly way and not spew a stack trace

**Comment by jondkent** [comment]
Perhaps the main point to document is the connecting from multiple ips is not an expected pattern?

**Comment by jondkent** [comment]
@raoulmillais @sublimino are you guys OK with this being a position issue, if so lets close this out

**Comment by s-irvine** [comment]
@jondkent If we're closing this issue I think we need a paragraph or so of explanation before (or as) this issue is closed. At the moment I don't think this discussion will inform anyone not already familiar with simulator why this will not be worked on. 

Also, I think there should be a new ticket created for @raoulmillais suggestion and linked here before this issue is closed.
