### ISSUE TITLE
Master Node IP Missing In Scenario Description

### ISSUE THREAD

**Issue by abdullahgarcia** [kubernetes-simulator/simulator#63]
For scenario: rbac-flanking-maneuver

The description contains a placeholder for the $MASTER_IP_ADDRESS, but this is not being resolved.

Please, see attached image.

<img width="569" alt="Screenshot 2019-11-11 at 16 41 57" src="https://user-images.githubusercontent.com/1493300/68604532-9937b780-04a2-11ea-8aeb-f19c6b9aa612.png">

**Comment by jondkent** [comment]
I think the way its presented in the challenge file is incorrect, the quotes are squashing the var.  Try removing the quotes around the var

**Comment by pi-unnerup** [comment]
I think I know the issue, let me fix this

**Comment by abdullahgarcia** [comment]
Fixed with pull request: https://github.com/kubernetes-simulator/simulator/pull/64
