### ISSUE TITLE
Make release fails on docker-test target.

### ISSUE THREAD

**Issue by jondkent** [kubernetes-simulator/simulator#67]
Currently getting the following error when running `make release`

<pre>
spawn simulator version

1.5736369583883626e+09  INFO     cmd/version.go:26       version v0.10

1.5736369583887901e+09  INFO     cmd/version.go:27       git commit c8472a90699d9572c64eceac5652141db0646577

1.5736369583898497e+09  INFO     cmd/version.go:28       build date 2019-11-13T09:18:55Z

++++ version_prints_ok PASSED
Sourced 0 Test Files.

Tests ended at Wed Nov 13 09:22:38 UTC 2019
run-tests.tcl:  Total   5       Passed  3       Skipped 0       Failed  2
Sourced 4 Test Files.
Files with failing tests: init.test
make: *** [docker-test] Error 1
</pre>

Possible down to AWS_SHARED_CREDENTIALS_FILE variable?

**Comment by s-irvine** [comment]
I managed to replicate this by attempting to run `make release` with incorrect AWS config. I'll add a validate requirements step to `make release` to see if that makes the error more obvious.
