### ISSUE TITLE
Do Not Mount `~/.ssh`

### ISSUE THREAD

**Issue by s-irvine** [kubernetes-simulator/simulator#78]
At the moment both `make run` and `kubesim` mount `~/.ssh` to store the ssh keys used to connect to the cluster. There is no obvious need to store the keys there since they could be in `~/.kubesim` instead. We are exposing unrelated user ssh keys to the container, something we should avoid as a matter of best practice.

**Comment by raoulmillais** [comment]
Good call. Let'f JFDI this :)
