### ISSUE TITLE
`simulator scenario launch ...` Cannot Run Without an Interactive Terminal

### ISSUE THREAD

**Issue by s-irvine** [kubernetes-simulator/simulator#85]
**Describe the bug**
Running `simulator scenario launch` without an interactive terminal leads to a failure without a relevant error message. I think the issue is to do with some of the bash terminal stuff that peturb does so #74 may help.

**To Reproduce**
1. Run:
```
docker run                                                          \
  -h launch                                                         \
  -v "${HOME}/.aws":/home/launch/.aws                \
  -v "${HOME}/.ssh":/home/launch/.ssh                         \
  -v "${HOME}/.kubesim":/home/launch/.kubesim                        \
  -e "AWS_ACCESS_KEY_ID"                                            \
  -e "AWS_SECRET_ACCESS_KEY"                                        \
  -e "AWS_REGION"                                                   \
  --rm --init  ${CONTAINER_NAME} -- bash -c  "simulator infra destroy; simulator infra create ; simulator scenario launch rbac-sangar"
```

**Expected behavior**
The scenario should provision correctly without failure.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: 19.03.4
 - Version of simulator: master-db0daa3180c5b7ae93b473ac40fc1236d8d2a00c

**Comment by jondkent** [comment]
@s-irvine would/has this been resolved when you refactored perturb?

**Comment by s-irvine** [comment]
I've done some testing and this appears to be resolved now. Closing the issue.
