### ISSUE TITLE
Set up a CODEOWNERS file for simulator then enable it for PRs to master.

### ISSUE THREAD

**Issue by jondkent** [kubernetes-simulator/simulator#88]

**Comment by s-irvine** [comment]
Accidentally closed this during the PR. I don't think this issue is done until PR CODEOWNERS enforcement is on in the repo options. Reopening until that has been enabled but we don't have plans to do that for a couple weeks at least.

**Comment by s-irvine** [comment]
Reopened as this is still a goal of the project.
