### ISSUE TITLE
Obfuscate the tasks.yaml file

### ISSUE THREAD

**Issue by jondkent** [kubernetes-simulator/simulator#93]
So people can't cat it from the attack container when the scenario starts.

**Comment by pi-unnerup** [comment]
additionally, align the output obfuscation where some scenarios send stout to null to run normally after this is done.

**Comment by jondkent** [comment]
added dying label as this has been outstanding for quite a while and I'm happy for this to be closed as 'won't fix'

**Comment by jondkent** [comment]
closing this as been labelled dying for a while now
